#!/usr/bin/env bash
# docker run -it --rm \
# 	-v $(pwd):/certs \
# 	-v $(pwd)/client:/client \
# 	--env-file $(pwd)/ca.env \
# 	--env-file $(pwd)/client.env \
# 	paulczar/omgwtfssl
# docker run -it --rm \
# 	-v $(pwd):/certs \
# 	-v $(pwd)/server:/server \
# 	--env-file $(pwd)/ca.env \
# 	--env-file $(pwd)/server.env \
# 	paulczar/omgwtfssl

sudo chown -R $USER:$USER ./**/*
chmod 0400 ./ca/ca-key.pem ./server/key.pem ./client/key.pem
chmod 0444 ./ca/ca-cert.pem ./server/cert.pem ./client/cert.pem

ln -s $(pwd)/ca/ca-cert.pem ${HOME}/.docker/ca.pem
ln -s $(pwd)/client/key.pem ${HOME}/.docker/key.pem
ln -s $(pwd)/client/cert.pem ${HOME}/.docker/cert.pem

sudo ln -s $(pwd)/ca/ca-cert.pem /opt/.docker/ca.pem
sudo ln -s $(pwd)/server/key.pem /opt/.docker/key.pem
sudo ln -s $(pwd)/server/cert.pem /opt/.docker/cert.pem

sudo ln -s $(pwd)/docker/daemon.json /etc/docker/daemon.json
