#!/usr/bin/env bash
root="$( cd $(dirname "$0") && pwd -P )/.."

create_client() {
	docker run -it --rm \
		-v ${root}:/certs \
		-v ${root}/client:/client \
		--env-file ${root}/ca.env \
		--env-file ${root}/client.env \
		paulczar/omgwtfssl
}

create_server() {
	docker run -it --rm \
		-v ${root}:/certs \
		-v ${root}/server:/server \
		--env-file ${root}/ca.env \
		--env-file ${root}/server.env \
		paulczar/omgwtfssl
}

ownership() {
	sudo chown -R $USER:$USER ${root}/**/*
	chmod 0400 ${root}/ca/ca-key.pem ${root}/server/key.pem ${root}/client/key.pem
	chmod 0444 ${root}/ca/ca-cert.pem ${root}/server/cert.pem ${root}/client/cert.pem
}

prepare_home() {
	ln -s ${root}/ca/ca-cert.pem ${HOME}/.docker/ca.pem
	ln -s ${root}/client/key.pem ${HOME}/.docker/key.pem
	ln -s ${root}/client/cert.pem ${HOME}/.docker/cert.pem
}

prepare_server() {
	sudo ln -s ${root}/ca/ca-cert.pem /opt/.docker/ca.pem
	sudo ln -s ${root}/server/key.pem /opt/.docker/key.pem
	sudo ln -s ${root}/server/cert.pem /opt/.docker/cert.pem
}

prepare_docker() {
	sudo ln -s ${root}/docker/daemon.json /etc/docker/daemon.json
}
